# Site settings
title: "Statement of PSICMI"
description: "A statement of PSICMI."
author: "PSICMI"

# Build settings
markdown: kramdown

# Statement settings
statement_title: "Psicmi : I can make it much better"
statement_subtitle: "by someone at psicmi.party"
statement_time: "2022-08-12 10:24"
