# Site settings
title: "Statement of PSICMI"
description: "A statement of PSICMI."
author: "PSICMI"

# Build settings
markdown: kramdown

# Statement settings
statement_title: "I opened the dictonary and started looking up what is love."
statement_subtitle: "-- psicmi"
statement_time: "2023-05-30 10:24"
